version: '3.1'
services:
  db:
    image: mysql
    container_name: agenda
    environment:
      MYSQL_ROTT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: